server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: false

  endpoints:
    web:
      exposure:
        include: health, info, metrics

  info:
    env:
      enabled: true

info:
  app:
    name: actuator-demo
    version: 1.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/menudb
    username: menu_user
    password: menu_pass
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    com.example.head16_springstablehigh: DEBUG